# Generated by Django 2.2 on 2020-06-14 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vender Name', max_length=80, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.CharField(help_text='Vender Address', max_length=280, null=True)),
                ('Location', models.CharField(choices=[('B', 'Bangalore'), ('C', 'Chennai'), ('M', 'Mumbai')], default='B', max_length=1, null=True)),
                ('landmark', models.CharField(max_length=80, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('I', 'In Progress'), ('R', 'Rejected')], default='I', max_length=1, null=True)),
                ('shop_image', models.ImageField(null=True, upload_to='venders')),
                ('bank_acc_no', models.IntegerField(blank=True, help_text='Bank Account Number.', null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=10, null=True)),
                ('document_verification', models.ImageField(null=True, upload_to='venders')),
                ('transport_mode', models.CharField(choices=[('A', 'Approved'), ('I', 'In Progress'), ('R', 'Rejected')], default='P', max_length=1, null=True)),
                ('ext_id', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer Name', max_length=80)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.CharField(help_text='Customer Address', max_length=280)),
                ('Location', models.CharField(choices=[('B', 'Bangalore'), ('C', 'Chennai'), ('M', 'Mumbai')], default='B', max_length=1)),
                ('landmark', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('I', 'In Progress'), ('R', 'Rejected')], default='I', max_length=1)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('staled', models.BooleanField()),
                ('ext_id', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
